CREATE TABLE IF NOT EXISTS list (id INTEGER PRIMARY KEY AUTOINCREMENT , name TEXT NOT NULL, description TEXT);
CREATE TABLE task (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, description TEXT, list_id INTEGER, status TEXT, CONSTRAINT fk FOREIGN KEY (list_id) REFERENCES list(id))


